---
- name: Rules for Ubuntu
  include_tasks: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
  tags: ["packages", "package"]

- name: Rules for Debian OS family
  include_tasks: debian.yml
  when: ansible_os_family == 'Debian'
  tags: ["packages", "package"]

- name: Rules for RedHat OS family
  include_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'
  tags: ["packages", "package"]
